import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Journey,V} from '../dist/journey.js';
const features=JSON.parse(fs.readFileSync(new URL('../dist/stars.json',import.meta.url))).features;
function make(){const j=new Journey(features,{seed:93741,balance:{fuel:22,credits:15,lifetime:500},velocity:[.12,.01,.02],mode:'plan'});j.setBudget({fuel:22,credits:15,lifetime:500});j.commit(j.quote('calibrate').id,{manual:true,investigation:true});return j;}
const fly=j=>{while(j.view().target)j.commit(j.quote(j.options()[0]).id,{manual:true});};
test('YOLO forecasts preserve state and quotes; default dire branch offers three finite targets',()=>{const j=make(),q=j.fieldQuote(),before=j.view(),f=j.missionForecast();assert.deepEqual(j.view(),before);assert.equal(j.assess(q.id).affordable,true);assert.equal(f.dire,true);assert.equal(f.homeFeasible,true);assert.equal(f.targets.filter(t=>t.routes.some(r=>r.affordable)).length,3);});
test('objective change preserves physical state and authority, extraction depletes only selected target, rewards do not renew caps',()=>{const j=make(),q=j.fieldQuote(),before=j.view();j.changeObjective('yolo','cinder');for(const k of ['position','velocity','resources','spent','budget','time'])assert.deepEqual(j.view()[k],before[k]);assert.equal(j.view().active,false);assert.throws(()=>j.commit(q.id,{manual:true}),/Stale/);const route=j.fieldQuote({destination:'asteroid',speed:.02});assert.ok(route.detail.miningComparison.totalYears<25);j.commit(route.id,{manual:true,enterDrive:true});fly(j);const ex=j.quote('extract');j.commit(ex.id,{manual:true});assert.throws(()=>j.commit(ex.id,{manual:true}),/Stale/);assert.equal(j.view().asteroids[0].deposit.fuel,0);assert.equal(j.view().asteroids[1].deposit.fuel,24);assert.equal(j.view().budget.fuel,22);j.pause();assert.throws(()=>j.changeObjective('yolo','cinder'),/unmined/);assert.throws(()=>j.changeObjective('yolo','tumble'),/limits/);const v=j.view();j.setBudget(Object.fromEntries(['fuel','credits','lifetime'].map(k=>[k,v.spent[k]+v.resources[k]])));j.changeObjective('yolo','tumble');assert.equal(j.assess(j.fieldQuote({destination:'asteroid',speed:.02}).id).affordable,true);const changed=j.view();j.changeObjective('home');assert.deepEqual(j.view().position,changed.position);assert.deepEqual(j.view().resources,changed.resources);assert.ok(j.fieldQuote({speed:.04}).detail.years>100);});
test('active field blocks objective switch; later coast can be abandoned without teleport or stale action',()=>{const j=make();j.commit(j.fieldQuote().id,{manual:true,enterDrive:true});j.pause();assert.throws(()=>j.changeObjective('yolo','cinder'),/field is still active/);j.resume();while(j.view().time<j.view().field.until-1e-9)j.commit(j.quote('coast').id);j.pause();const before=j.view(),old=j.quote('coast');j.changeObjective('home');assert.deepEqual(j.view().position,before.position);assert.deepEqual(j.view().velocity,before.velocity);assert.deepEqual(j.view().resources,before.resources);assert.equal(j.view().target,null);assert.throws(()=>j.commit(old.id,{manual:true}),/Stale/);});
test('upfront fuel and credit permissions block mining even with rich reward',()=>{const j=make();j.setBudget({fuel:13,credits:7,lifetime:500});const before=j.view();assert.equal(j.missionForecast().targets.some(t=>t.routes.some(r=>r.affordable)),false);assert.throws(()=>j.changeObjective('yolo','cinder'),/limits/);assert.deepEqual(j.view(),before);});
test('mining quotes reconcile future extraction credits and actual sunk survey receipts',()=>{for(const surveyed of [false,true]){const j=make();if(surveyed)j.commit(j.quote('survey').id,{manual:true,investigation:true});j.changeObjective('yolo','cinder');const m=j.fieldQuote({destination:'asteroid',speed:.02}).detail.miningComparison;assert.equal(m.futureCreditsSpent,2);assert.equal(m.reportCreditsPaid,surveyed?3:0);assert.equal(m.totalCreditsSpent,surveyed?5:2);assert.equal(m.netCredits,8-m.totalCreditsSpent);assert.equal(j.view().report.reportCreditsPaid,surveyed?3:0);}});
